# Generated by Django 2.1.5 on 2019-04-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Opened', 'opened'), ('Finished', 'finished'), ('Canceled', 'canceled')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('Hous', 'household'), ('GAD', 'Gadget'), ('TEL', 'TV')], max_length=2),
        ),
    ]
