# Generated by Django 4.2.4 on 2023-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190405_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('HH', 'household'), ('GAD', 'Gadget'), ('TEL', 'TV')], max_length=3),
        ),
    ]
